### ISSUE TITLE
Add Whisper for auto transcription

### ISSUE THREAD

**Issue by platform-kit** [cuuupid/cog-f5-tts#1]
Hi there, thanks for porting this to Cog/Replicate.

Would you be willing to add auto-transcription via Whisper?  See this demo on huggingface where it has already been implemented:

https://huggingface.co/spaces/mrfakename/E2-F5-TTS

And while we're at it, any interest in implementing the speech-editing feature as well?

Thanks again!

**Comment by cuuupid** [comment]
Hi! Auto transcription should already work (if you don't add reference text, it will automatically transcribe it).

I can look at speech editing, and folding in the chunking improvements.

**Comment by platform-kit** [comment]
@cuuupid awesome. I would be super grateful for that.

**Comment by platform-kit** [comment]
@cuuupid also, when doing inference without a transcription input, I get this error:

`'NoneType' object has no attribute 'strip'`


```
Generating: captain teemo, on duty!
[*] Converting reference audio...
[!] Audio is over 15s, clipping to only first 15s.
[+] Converted reference audio.
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/cog/server/worker.py", line 349, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 342, in predict
if not ref_text.strip():
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```
